version: '2'

services:
  mopidy:
    image: 'wernight/mopidy'
    volumes:
      - ./media:/var/lib/mopidy/media:ro
      - ./local:/var/lib/mopidy/local
      - ./mopidy-cmd.sh:/mopidy-cmd.sh
      - ./podcasts.opml:/podcasts.opml:ro
      - ./mopidy.conf:/etc/mopidy/mopidy.conf
    command: /mopidy-cmd.sh
    env_file: mopidy.env

