version: '2'

services:
  nextcloud:
    image: 'nextcloud'
    volumes:
      - nextcloud-data:/var/www/html
      - ./my.config.php:/var/www/html/config/my.config.php:ro
    env_file: nextcloud.env

